---
title: "epicollect field sample metadata"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
# Tidy epicollect data

library(here)
library(tidyverse)
library(janitor)
library(lubridate)
library(kableExtra)

raw_epi <- read_csv(here("data/field_sample_meta/form-1__radiometer.csv"))
final_list <- read_csv(here("data/field_sample_meta/final_sample_list.csv"))

glimpse(raw_epi)

epi_select <- raw_epi %>% 
  # rename for convenience
  rename(datetime = created_at, 
         sample_id = `1_ID`, 
         lat = lat_2_coords, 
         lon = long_2_coords,
         scan_strings = `5_notes`, # the sed file number
         container_type = `6_algae_container_ty`,
         weight_g = `7_wt_g`) %>% 
  # discard unused cols
  select(datetime, sample_id, lon, lat, scan_strings, container_type, weight_g) %>% 
  # extract date
  mutate(date = as_date(datetime),
         sample_id = sample_id %>% tolower(),
         .after = sample_id) 
epi_select
```


```{r}
# what is the mean snow density? assuming pi*5cm^2 * 2 cm volume = 157 ml
epi_select %>% 
  mutate(snow_density = weight_g/157) %>% # in g/ml, see wiki firn snow density
  select(sample_id, snow_density) %>% 
  ggplot(aes(snow_density)) +
  geom_histogram()

# the tidy_radiometer data are grouped by scan_id, in the format 20210803_00001
# split each string into chr vector containg each scan_id that pertains to that sample  

# # test
# "sed 111-113" %>% 
#   str_extract_all("[:digit:]+") %>% 
#   unlist() %>% 
#   as.numeric() %>% 
#   reduce(seq)
# # end test
```


```{r}
get_vec_of_scan_ids <- function(str){
  str %>% 
    str_extract_all("[:digit:]+") %>% 
    unlist() %>% 
    as.numeric() %>% 
    reduce(seq) %>% 
    map_chr(str_pad, 5, pad = "0")
}
# "sed 111-113" %>% get_vec_of_scan_ids() #test

# apply the function to the list
scan_str_list <- epi_select$scan_strings %>% 
  as.list() %>% 
  map(get_vec_of_scan_ids)

epi_scan_id <- epi_select %>% 
  mutate(scan_strings = scan_str_list) %>% # replace the old with the new list, better way to do this?
  unnest_longer(scan_strings) %>% 
  mutate(scan_id = str_glue("{date}_{scan_strings}") %>% 
           str_remove_all("-"),
         .keep = "unused")
```


```{r}
epi_scan_id %>% 
  filter(!str_detect(scan_id, "NA")) %>% 
  write_csv(here("data/field_sample_meta/tidy_epicollect.csv"))
```


```{r}
# make a table of sample metadata

kk <- epi_select %>% 
  mutate(sample_id = sample_id %>% str_remove("21.0"),
         sample_id = sample_id %>% str_remove("21.")) %>% # remove the 21 and unpad 0 for simplicity 
  inner_join(final_list) %>% 
  # convert to local time
  mutate(datetime = datetime - hours(8)) %>% 
  select(sample_id, type, lat, lon, datetime) 

kk2 <- kk %>% 
  kbl(caption = "A. Radiometer samples", col.names = c("Sample ID", "Snow Color", "Latitude", "Longitude", "Date/Time (PST)")) %>% 
  kable_classic(full_width = F, html_font = "Cambria") 
kk2

```


```{r}
kk2 %>% 
  save_kable(here("figs/radiometer_sample_table.pdf"))
```
```{bash}
# the density parameter must come before the input file
convert \
  -density 300 \
  ../figs/cat_sample_table.pdf \
  -sharpen 0x1.0 \
  -quality 100 \
  ../figs/cat_sample_table.png
```

